name: polymetis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip

  # Build dependencies
  - assimp
  - doxygen
  - eigen
  - grpc-cpp
  - hpp-fcl
  - libprotobuf
  - mkl-include
  - mkl
  - openmpi
  - pinocchio
  - poco  # needed by libfranka
  - urdfdom
  - urdfdom_headers
  - yaml-cpp

  # Run dependencies
  - asv
  - black
  - boost
  - boost-cpp
  - breathe
  - dash
  - grpcio
  - mujoco
  - hydra-core
  - importlib-resource
  - myst-parser
  - numpy
  - pandas
  - plotly
  - protobuf
  - pybullet
  - pymodbus
  - pyserial
  - pytest
  - pytest-benchmark
  - scipy
  - spdlog
  - sphinx
  - sphinx-copybutton
  - sphinx-book-theme
  - tqdm
