name: polymetis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip

  # Build dependencies
  - eigen
  - pinocchio<3.0
  - libprotobuf=3.18
  - yaml-cpp=0.7
  - grpc-cpp=1.42

  # Run dependencies
  - protobuf=3.18
  - grpcio==1.42
