name: polymetis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip

  # Build dependencies
  - eigen
  - libprotobuf=3.18
  - pinocchio<3.0

  # Run dependencies
  - protobuf=3.18
