channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip

  # Build dependencies
  - eigen
  - numpy>=2.0
  - pinocchio
  - libprotobuf=3.20
  - yaml-cpp
  - grpc-cpp=1.46
  - spdlog

  # Run dependencies
  - protobuf=3.20
  - grpcio=1.46
